apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 192.168.56.105:8082/git-jenk-maven-nexus-docker-kube:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: nexus-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
